blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/NeogitOrg/neogit/discussions 
    about: Usage questions and support requests are answered in the discussions
