name: Tests

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [stable, nightly]
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          mkdir -p ~/.local/share/neogit-test/site/pack/plenary.nvim/start
          cd ~/.local/share/neogit-test/site/pack/plenary.nvim/start
          git clone https://github.com/nvim-lua/plenary.nvim

          mkdir -p ~/.local/share/neogit-test/site/pack/telescope.nvim/start
          cd ~/.local/share/neogit-test/site/pack/telescope.nvim/start
          git clone https://github.com/nvim-telescope/telescope.nvim

      - name: Install Neovim
        run: |
          wget https://github.com/neovim/neovim/releases/download/${{ matrix.release }}/nvim-linux64.tar.gz
          tar -zxf nvim-linux64.tar.gz
          sudo ln -s $(pwd)/nvim-linux64/bin/nvim /usr/local/bin

      - name: Test
        continue-on-error: false
        env:
          ci: "1"
        run: |
          make test
