name: Tests

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [v0.10.0, nightly]
    env:
      CI: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: nvim-lua/plenary.nvim
          path: tmp/plenary/

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: nvim-telescope/telescope.nvim
          path: tmp/telescope/

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.release }}

      - name: E2E Test
        run: |
          bundle exec rspec

      - name: Install Dependencies
        run: |
          mkdir -p ~/.local/share/neogit-test/site/pack/plenary.nvim/start
          cd ~/.local/share/neogit-test/site/pack/plenary.nvim/start
          git clone https://github.com/nvim-lua/plenary.nvim

      - name: Unit Test
        run: |
          make test
